version: '3'
services:
  univitrina-frontend:
    image: "nginx:1.20.1-alpine"
    container_name: univitrina-frontend
    network_mode: host
    volumes:
      - "./univitrina-front/build/://usr/share/nginx/html:ro"
      - "./univitrina-front/nginx.conf://etc/nginx/conf.d/default.conf:ro"    
  univitrina-postgres:
    image: postgres
    container_name: univitrina-postgres
    ports:
      - 5432:5432
    volumes:
      - "./pg_data:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: univitrina
      POSTGRES_DB: univitrina
      PGDATA: /var/lib/postgresql/data/pgdata
  univitrina-backend:
     image: "univitrina-backend"
     container_name: univitrina-backend
     volumes:
      - "./univitrina-backend/src/etc:/app/etc:ro"
     depends_on:
      - univitrina-postgres
     ports:
      - 4000:4000
     restart: always
